### ISSUE TITLE
python module directory imports not being recognized

### ISSUE THREAD

**Issue by owenns** [christinanguyen1/JIB-307-GITogether#2]
ideally for the sake of good project structure, id like to keep separate components of the backend in different directories (`pydb` for database stuff, `pyserv` for general HTTP server stuff) but there is an issue where trying to import the `pydb.pydb_api` module is coming up as a ModuleNotFoundError. Any help with fixing this issue is greatly appreciated.

**Comment by bangtimothy** [comment]
tried to find a couple solutions for this but i've only been able to come up with two solutions:
 - we either move the login.py file to the py_backend directory (so it contains the pyserv and pydb paths)
 - or we run the command: 
export PYTHONPATH=.
in the py_backend directory and then run login.py which forces py to include the pydb in the path so it can search for it
