### ISSUE TITLE
flask not rendering site assets

### ISSUE THREAD

**Issue by owenns** [christinanguyen1/JIB-307-GITogether#3]
for flask to send someone an HTML webpage as a GET request, it needs to call `render_template("example.html")`, and expects all such front-end files (images, assets, html/css files) to exist within a folder called `templates` in the same directory as the python file calling it. i managed to render the html on page but not the associated CSS or assets/icon. this might be as simple as copying all the files/folders into the `py_backend/pyserv/templates` folder

**Comment by joonpark157** [comment]
moving css file and image to templates folder didn't change anything

**Comment by joonpark157** [comment]
Alright, so I need someone to take a look to see if I rendered stuff right. But for now, it seems like the python file rendered CSS and images correctly.

**Comment by christinanguyen1** [comment]
The issue was still there. Turns out what had to be done was move assets and the css file into pyserv/static and the directory to link the css to the htmls needed to be updated. I will push the change soon.
